use_frameworks!

target 'FTLinearActivityIndicator_Example' do
  pod 'FTLinearActivityIndicator', :path => '../'

  target 'FTLinearActivityIndicator_Tests' do
    inherit! :search_paths
	
	    post_install do |installer|
      installer.pods_project.targets.each do |target|
        
        if ['FTLinearActivityIndicator'].include? target.name
          target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
          end
        end

        end
      end

    
  end
end
